### ISSUE TITLE
[Quick Tour] Issue in project initialization

### ISSUE THREAD

**Issue by karu95** [ballerina-platform/ballerina-www#959] opened 2018-07-02 16:26 UTC
**Description:**
When initializing the project using _ballerina init_ command, _Ballerina.toml_ doesn't get created. So, at the "Push your Package to Ballerina Central" stage, there is a confusion because _Ballerina.toml_ file is missing. 

**Steps to reproduce:**
Documentation should be changed as initialize the project using _ballerina init -i_ and create the _Ballerina.toml_.

**Comment by NatashaWso2** [comment] 2018-07-09 09:00
We have fixed this issue by creating Ballerina.toml when a initializing a project using _ballerina init_. This fix is available in 0.976.1-SNAPSHOT.  Closing this issue, since the issue is fixed.

**Closed by NatashaWso2** 2018-07-09 09:00 UTC
