### ISSUE TITLE
[Quick Tour - Create a New Package] - Calculator : Redeclaration of C variable 

### ISSUE THREAD

**Issue by KrishiHw** [ballerina-platform/ballerina-www#991] opened 2018-07-09 04:35 UTC
The `c` variable is redeclared in the code given in the documentation when creating the `main.bal` file.

       int c = 0;
        while ( c != 5) {
        // print options menu to choose from
        io:println("Select operation.");
        io:println("1. Add");
        io:println("2. Subtract");
        io:println("3. Multiply");
        io:println("4. Divide");
        io:println("5. Exit");

        string choice = io:readln("Enter choice 1 - 5: ");
        int c = check <int>choice;`

It should be appended as,
` c = check <int>choice`

**Comment by yohanym95** [comment] 2018-07-09 11:17
when i build a calculator then give a error like this.then i change c varibale like this,
c = check choice;
but nothing happend.
error: sami/calculator:0.1.0\main.bal:3:1: redeclared symbol 'main'
compilation contains errors

**Comment by KrishiHw** [comment] 2018-07-09 15:43
The error you have mentioned refers to a redeclaration of `main` not the `c` variable addressed by the issue.

**Comment by yohanym95** [comment] 2018-07-09 16:03
that error is fixed.

**Comment by nadeeshaan** [comment] 2018-07-11 03:29
Duplicate of https://github.com/ballerina-platform/ballerina-www/issues/984. Hence closing the issue

**Closed by nadeeshaan** 2018-07-11 03:29 UTC
