### ISSUE TITLE
[Composer] Cannot create new file within folder using composer when the same folder was opened as two projects in single window.

### ISSUE THREAD

**Issue by rameshka** [ballerina-platform/ballerina-www#1043] opened 2018-07-18 01:58 UTC
**Description:**
When a folder and a sub folder within the same project are opened as two projects, new files cannot be created in sub folder using the composer (accessing through any of the two opened projects) 

**Suggested Labels:**
Component/Composer
bug

**Suggested Assignees:**

**Affected Product Version:**
v0.975.1

**OS, DB, other environment details and versions:**
Ubuntu 16.04

**Steps to reproduce:**
Using file manager, create a folder called “ballerina_folder”. Then add a sub folder to that folder as “ballerina_sub_folder”.
Start composer, click “open new project”, select “ballerina_folder” and open it.
On the same window, click “open new project”, select the “ballerina_sub_folder” and open it.
Then try to create new file within “ballerina_sub_folder” using any of the two projects.

**Related Issues:**

**Comment by nadeeshaan** [comment] 2018-07-20 03:43
@rameshka can you try this in the latest released version v0.980.1. This issue cannot reproduce in the latest release and hence closing. Please reopen if the issue can further observe

**Closed by nadeeshaan** 2018-07-20 03:43 UTC
