### ISSUE TITLE
calculator:0.0.0/main.bal:3:1: extraneous input 'import'

### ISSUE THREAD

**Issue by Kushan989** [ballerina-platform/ballerina-www#1021] opened 2018-07-13 16:45 UTC
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ldclakmal** [comment] 2018-07-31 04:55
@Kushan989 Can you please explain the issue and provide the steps to reproduce?

**Comment by Manuri** [comment] 2018-08-20 10:09
@Kushan989 Do you mean that, when you create a new ballerina file in Idea/Composer/VSCode an unnecessary package statement gets added to the file? 
Please let us know exact steps with which IDE/plugin you used to reproduce this.

**Comment by NatashaWso2** [comment] 2018-09-12 07:00
@Kushan989  I tried to reproduce the issue by creating a new ballerina file in Composer, VSCode or Idea but couldn't do so. Since this is not reproducible I'm closing the issue. Please reopen the issue if you still encounter it.

**Closed by NatashaWso2** 2018-09-12 07:00 UTC
Labels: Community Page
